### ISSUE TITLE
Adding examples with more complex dynamical systems

### ISSUE THREAD

**Issue by gy2256** [maxhcohen/ControlBarrierFunctions.jl#21]
Great job on creating this package. Are there any plans to add more examples with complex dynamics, such as the kinematic bicycle model or quadcopter model?

**Comment by maxhcohen** [comment]
Hey Guang, thanks! I do plan to add more complex examples over time, but I'm also open to anyone contributing examples if they have interesting ones to add. I do have an example for a quadrotor using similar functionalities in a different repo https://github.com/maxhcohen/ReducedOrderModelCBFs.jl/blob/main/examples/LCSS/full_quad_sim2.jl that I'll try to port over if I get some free time.

**Comment by gy2256** [comment]
Thanks Max!
